# Generated by Django 6.0.4 on 2026-04-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_endpoint_dynamicdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
